#默认配置了ERROR、WARN和INFO级别的日志输出到控制台
#切换至debug级别
debug: true
#多彩输出
spring.output.ansi.enabled: DETECT

logging:
    #日志以文件输出
    path: ./logs
    #级别控制
    level:
        org.springframework.web: OFF
        org.mybatis: OFF
        com.zjmy.account: DEBUG
        org.springframework.security: INFO

server.tomcat:
    access-log-enabled: true
    access-log-pattern: '%h %l %u %t "%r" %s %b %D'
    basedir: ./logs

#web应用服务器
server:
    address: localhost
    port: 8888
    sessionTimeout: 1800
    contextPath: /
    
#HTTPS支持
server.ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat    
    
#数据库连接信息   
#spring.datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root

#mybatis配置信息
mybatis:
    mapperLocations: /mappers/**/*.xml
    type-aliases-package: com.zjmy.account.model

#druid数据库连接池
spring.datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

#测试@Value("${属性名}")注解来加载对应的配置属性
user:
  name: liupeng
  showName: 刘鹏

spring.thymeleaf:
    cache: false 
    check-template-location: true
    content-type: text/html 
    enabled: true 
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5 
    prefix: classpath:/templates/ 
    suffix: .html
    template-resolver-order: 
